id: P000061
initial_creation_type: ebook
source_metadata:
  title: ༄༅། །ངེས་དོན་གྱི་ལྟ་སྒོམ་ཉམས་སུ་ལེན་ཚུལ་ཇི་ལྟ་བར་སྟོན་པ་རྡོ་རྗེའི་མདོ་འཛིན་ཞེས་བྱ་བ་ལ་ལྡེབ།
    །
  authors:
  - མཛད་པ་པོ། མཁས་གྲུབ་ཆེན་པོ་རྩེ་ལེ་སྣ་ཚོགས་རང་གྲོལ།
  layers:
  - book_title
  - author
  - chapter_title
  - yigchung
  id: TSD-TSE-01
created_at: '2020-01-31T11:06:29.902795'
last_modified_at: '2021-11-25T11:06:29.902795'
statistics:
  total_words: 7639
  total_non_words: 811
quality:
  non_words_ratio: 0.11
